apiVersion: v1
kind: Service
metadata:
  name: game-2048-service
  namespace: game
  labels:
    app: game-2048
spec:
  selector:
    app: game-2048
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
